services:
  migrate:
    volumes:
      - ./api:/app

  api:
    volumes:
      - ./api:/app

  worker:
    volumes:
      - ./api:/app

  beat:
    volumes:
      - ./api:/app

  web:
    volumes:
      - ./web:/app
