# Generated by Django 5.2.15 on 2026-06-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='skip_watering',
            field=models.BooleanField(default=False),
        ),
    ]
