# Generated by Django 5.2.15 on 2026-06-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_location_skip_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcarelog',
            name='type',
            field=models.CharField(blank=True, choices=[('watered', 'Watered'), ('repotted', 'Repotted')], default=None, max_length=20, null=True),
        ),
    ]
