# Generated by Django 5.2.15 on 2026-06-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plantcarelog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plants.plantimage'),
        ),
    ]
