# Generated by Django 5.2.15 on 2026-06-24 15:48

import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plant_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(upload_to=plants.models.plant_image_upload_to),
        ),
    ]
