# Generated by Django 5.2.15 on 2026-06-24 15:53

from django.db import migrations, models


def backfill_taken_at(apps, schema_editor):
    PlantImage = apps.get_model('plants', 'PlantImage')
    PlantImage.objects.filter(taken_at__isnull=True).update(taken_at=models.F('uploaded_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plantimage_upload_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_taken_at, migrations.RunPython.noop),
    ]
