# Generated by Django 5.2.15 on 2026-06-25 10:21

import plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_seed_watering_interval_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=plants.models.plant_thumbnail_upload_to),
        ),
    ]
