# Generated by Django 5.2.15 on 2026-07-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_seed_fertilizing_interval_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='cutting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
