# Generated by Django 5.2.15 on 2026-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_plant_cutting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='cutting_date',
            new_name='propagation_date',
        ),
    ]
