# Generated by Django 5.2.15 on 2026-07-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_rename_cutting_date_plant_propagation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
